# docker-compose.dev.yml
services:

  # 1️⃣ Init (db + default user)
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-init
    restart: "no"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: "/opt"
    volumes:
      - ./:/opt
      - ./requirements-airflow.txt:/requirements.txt
    entrypoint: >
      bash -c "
        airflow db init &&
        airflow users create --username admin \
          --firstname Admin --lastname User \
          --role Admin --email admin@example.org \
          --password admin || true
      "

  # 2️⃣ Webserver
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-web
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: "/opt"
    volumes:
      - ./:/opt
      - ./requirements-airflow.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow webserver"

  # 3️⃣ Scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-sched
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      PYTHONPATH: "/opt"
    volumes:
      - ./:/opt
      - ./requirements-airflow.txt:/requirements.txt
    command: >
      bash -c "airflow scheduler"

  # 4️⃣ MLflow server
  mlflow:
    build: ./mlflow-server
    container_name: mlflow
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/app/mlruns

volumes:
  mlruns:
